### PR TITLE
Netflow

### PR DESCRIPTION
**Pull request by jeremycx**
Hi there.

Thanks for the Netfow work! I reorganized your netflow module to confirm to what npm likes for automated installation.

If you accept this pull request, please review the LICENCE file to ensure you agree with the MIT licence.

### CODE REVIEW

**Comment by Sghazzawi** [comment]
Jeremy,

Thank you so much for the contributions. My silly "for pay" job got hectic
recently and I haven't had time to get back to it.  A few things:
1. How familiar are you with netflow? I can use help on this and if you
   are knowledgeable on it, I'd be glad to make you a contributor.
2. I originally didn't want to put it on NPM until I had the Netflow V9
   functionality worked out, but now I'm thinking release sooner rather than
   later
3. I was considering releasing this under GPL, but I'm a bit fuzzy on the
   finer points between them, can you give me a quick synopsis.

Again, thank you so much for this, and if at all possible, I'd love more of
your help.

Sharif

On Mon, Apr 2, 2012 at 4:08 PM, Jeremy Childs <
reply@reply.github.com

**Comment by jeremycx** [comment]
Glad to help!

I'm integrating your work into a current project, so I'll have a vested interest in making sure everything is working ok. I'll hit you with more pull requests if I find any problems.

I've done a lot of work with netflow in the (distant) past, so I'm pretty familiar with it up till version 5. V9 is a total mystery to me, however. I might do some research in the next couple of weeks, but I wouldn't count on any immediate results from my end.

Yes, I think you should release sooner - better to (1) make the project as public as possible early and (2) demonstrate you're open to pull requests. This will funnel any development effort out there toward your project, even if it's not perfect. Nothing worse than having 23.5 different modules out there for the same functionality.

MIT vs GPL: MIT is pretty much the most liberal licence there is -- people can take the code and do whatever they want. If you add your own name in the LICENCE file, then any users will need to reprint your name if they use it. No other restrictions.

Google GPL/LGPL (there are lots of introductory tutorials for the non-legal minded) to find out about those licences, but they're more restrictive.

**Comment by Sghazzawi** [comment]
Jeremy, just pushed to NPM.  Thank you much for your help.  Also, applied the MIT license to it.

**Comment by jeremycx** [comment]
Awesome, thanks. I'll drop you a note once I've beaten the tar out of the module. Looks good so far, though.

**Comment by imanviii** [comment]
Hi there
Is it netflow 9 supported now?
im going to use node.js and Netflowd on a monitoring app and want to know that if it capable of collecting netflow v9.
thanks

**Comment by Sghazzawi** [comment]
Netflow v9 support us not complete yet. I will however bump it up the top
of the priority list and keep you posted as to progress.

Thanks

On Jan 17, 2013, at 12:11 PM, imax36581 notifications@github.com wrote:

Hi there
Is it netflow 9 supported now?
im going to use node.js and Netflowd on a monitoring app and want to know
that if it capable of collecting netflow v9.
thanks

—
Reply to this email directly or view it on
GitHubhttps://github.com/Sghazzawi/Node-Netflowd/pull/2#issuecomment-12377931.

**Comment by imanviii** [comment]
thanks
but you think how long does it take to be completed? i mean estimated time.
i ask that because my app completely depend on this component :D 
thanks in advance

**Comment by shaofis** [comment]
I'm actually very close on NetFlow V9 and IPFIX V10. I've made some base changes; I'm only working with NetFlowPacket; but you should be able to use what I have as a starting point for adding V9 and V10 back into Netflowd.

I'll get it posted up as soon as I finish a few things.

**Comment by shaofis** [comment]
For what it's worth you are welcome to use any bits or pieces to speed this request along.

https://github.com/shaofis/Node-Netflowd/blob/master/README.md

V9 and V10 are similar in nature and could probably be done inline; but for the sake of my sanity while working out the details of V10 I've split it off into it's own sections.

**Pull request closed without merging**
